### ISSUE TITLE
To-Do App: Change the background color

### ISSUE THREAD

**Issue by LittleMonksStudio** [CEN3031GroupA/workflow#1]
Update the background color of the To-Do App to whatever you would like (no restrictions)

- [ ] Clone the repository to your local drive

- [ ] Create a branch to develop your changes and commit to git

- [ ] Review code with Scrum Master and correct if necessary
