### ISSUE TITLE
To-Do App: Add ability to set a priority to to-do a item

### ISSUE THREAD

**Issue by LittleMonksStudio** [CEN3031GroupA/workflow#2]
Create a way to set a priority to a to-do item.  Example priorities include Now, Tomorrow, Someday.

- [x] Clone the repository to your local drive

- [x] Create a branch to develop your changes and commit to git

- [ ] Review code with Scrum Master and correct if necessary
