### ISSUE TITLE
To-Do App: Add an edit button with appropriate functionality

### ISSUE THREAD

**Issue by LittleMonksStudio** [CEN3031GroupA/workflow#3]
Create an edit button consistent with the app style and develop functionality to allow editing of a to-do item.

- [x] Clone the repository to your local drive

- [x] Create a branch to develop your changes and commit to git

- [x] Review code with Scrum Master and correct if necessary
