### ISSUE TITLE
To-Do App: Add a button to mark a to-do item is complete

### ISSUE THREAD

**Issue by LittleMonksStudio** [CEN3031GroupA/workflow#4]
Create a button consistent with the app style to mark a to-do item complete.

- [x] Clone the repository to your local drive

- [x] Create a branch to develop your changes and commit to git

- [ ] Review code with Scrum Master and correct if necessary

**Comment by LittleMonksStudio** [comment]
no fix
