### ISSUE TITLE
To-Do App: Show the total number of items in the to-do list at above the list

### ISSUE THREAD

**Issue by LittleMonksStudio** [CEN3031GroupA/workflow#5]
This number should change when items are added and deleted.

- [ ] Clone the repository to your local drive

- [ ] Create a branch to develop your changes and commit to git

- [ ] Review code with Scrum Master and correct if necessary

**Comment by LittleMonksStudio** [comment]
no fix
