### ISSUE TITLE
To-Do App: A button to clear all completed tasks

### ISSUE THREAD

**Issue by LittleMonksStudio** [CEN3031GroupA/workflow#6]
All completed tasks should be eliminated from the list.

- [x] Clone the repository to your local drive

- [x] Create a branch to develop your changes and commit to git

- [ ] Review code with Scrum Master and correct if necessary

**Comment by LittleMonksStudio** [comment]
All completed tasks should be eliminated from the list.

- [ ] Clone the repository to your local drive

- [ ] Create a branch to develop your changes and commit to git

- [ ] Review code with Scrum Master and correct if necessary

**Comment by LittleMonksStudio** [comment]
All completed tasks should be eliminated from the list.

- [ ] Clone the repository to your local drive

- [ ] Create a branch to develop your changes and commit to git

- [ ] Review code with Scrum Master and correct if necessary

**Comment by LittleMonksStudio** [comment]
no fix
