### ISSUE TITLE
To-Do App: Add functionality to enter a to-do item upon hitting enter key

### ISSUE THREAD

**Issue by LittleMonksStudio** [CEN3031GroupA/workflow#7]
When entering a new to-do item, update it so that the app will except the enter key as a form of completing the entry.  The functionality should mimic what occurs when the add button is used.

- [x] Clone the repository to your local drive

- [x] Create a branch to develop your changes and commit to git

- [x] Review code with Scrum Master and correct if necessary
